### ISSUE TITLE
Safari doesn't clear buffer, while chrome does.

### ISSUE THREAD

**Issue by roelvanhintum** [mrdoob/three.js#12598]
Rendering in Safari doesn't clear the frame for each render, causing clutter.
Some more testing revealed that it's just on macs with the "Intel Iris Pro 1536 MB".

You can edit for small-test.  
https://jsfiddle.net/z0zd711z/

##### Three.js version

- [x] r88

##### Browser

- [ ] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer
- [x] Safari (really just on MacOS, iOS is fine)

##### OS

- [ ] All of them
- [ ] Windows
- [x] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

##### Hardware Requirements (graphics card, VR Device, ...)

Graphics: Intel Iris Pro 1536 MB

![screen shot 2017-11-07 at 11 12 27](https://user-images.githubusercontent.com/1023734/32493593-b2eff81c-c3be-11e7-8b24-34fd6f931f73.png)

**Comment by Mugen87** [comment]
Are you on the newest OS X version? AFIAK, on Mac OS graphics driver are automatically upgraded by upgrading to a newer version of the operating system.

Independently, i'm not sure we can help here. This seems to be a driver related/OS specific problem. You should submit a bug report to Apple: https://developer.apple.com/bug-reporting/

**Comment by roelvanhintum** [comment]
Yes, i'm runnig High Sierra (10.13 (17A405)).

The weird thing is that some examples are running normal. I just couldn't find why.

**Comment by Mugen87** [comment]
🤔

**Comment by Mugen87** [comment]
I'm also on High Sierra (10.13.1) and can't reproduce with Safari (11.0.1). However, i have an AMD GPU.

**Comment by roelvanhintum** [comment]
@Mugen87 I did test this on other macs and it's just the ones with a "Intel Iris Pro 1536 MB", so far. One of the machines is a iMac (21.5-inch, Late 2013).

**Comment by johanhenrikssn** [comment]
Can confirm this on High Sierra (10.13.1) with Safari (11.0.1) with Intel Iris Pro 1536 MB. I have a MacBook Pro (Retina, 15-inch, Late 2013) with a discrete graphics card in it as well (NVIDIA GT 750M), and when manually switching between both of them, its only occurring when on Intel Iris Pro.

**Comment by oleksmarkh** [comment]
Can also confirm for the following configuration:
* MacBook Pro (Retina, 13-inch, Early 2015)
* Intel Iris Graphics 6100 1536 MB
* macOS High Sierra `v10.13.1`
* Safari `v11.0.1 (13604.3.5)`

Occurred after updating to High Sierra.

**Comment by kenrussell** [comment]
Whatever the bug was, Apple seems to have fixed it in 10.13.2. Your fiddle works correctly in the 10.13.2 beta.

You might want to sign up for Apple's beta program so you can try early-access OS releases and report bugs earlier. It seems that several graphics driver bugs were introduced in 10.13 and we're still working on getting to the bottom of all of them. Happy to help highlight bugs to Apple. Reduced test cases are especially appreciated.

**Comment by grorg** [comment]
We got similar reports about this. I'm not sure what went wrong - I don't think it was a WebKit issue because I tried various versions of Safari on this exact hardware and didn't see an issue. I'm glad to hear it has been resolved.

**Comment by filidutten** [comment]
Can confirm this only located to Safari 11.0.1 and High Sierra. However it's not resolved..

**Comment by roelvanhintum** [comment]
Solved it for now with @AkeluX 's suggestion of adding a transparent plane behind the scene.
https://github.com/NASAWorldWind/WebWorldWind/issues/379#issuecomment-348258663

example: https://jsfiddle.net/z0zd711z/3/
