### ISSUE TITLE
examples/webgl_shadowmap.html : no shadow on the ground in dev

### ISSUE THREAD

**Issue by mbredif** [mrdoob/three.js#14632]
##### Description of the problem

The current version (141c3d2b99d5633af625e7bbb3f0e9d2d8a1f57c) of [examples/webgl_shadowmap.html](https://rawgit.com/mrdoob/three.js/141c3d2b99d5633af625e7bbb3f0e9d2d8a1f57c/examples/webgl_shadowmap.html) casts no shadow on the ground. (shadows on the other objects are ok)

##### Three.js version

- [X] Dev
- [ ] r95
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [ ] Windows
- [ ] macOS
- [X] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
Should be solved via #14617

**Comment by mbredif** [comment]
Unfortunately not for me : #14617 has been merged (73c2accb93111a0bca0db51e2efdd3e220c1c549) and I still see the issue:
- [examples/webgl_shadowmap.html in 73c2acc](https://rawgit.com/mrdoob/three.js/73c2accb93111a0bca0db51e2efdd3e220c1c549/examples/webgl_shadowmap.html)
- [examples/webgl_shadowmap.html in dev](https://rawgit.com/mrdoob/three.js/dev/examples/webgl_shadowmap.html)

**Comment by Mugen87** [comment]
The build files are not update yet.

**Comment by mbredif** [comment]
I confirm the fix with locally built files. thanks !
