### ISSUE TITLE
Webcam example does not work in Safari

### ISSUE THREAD

**Issue by sachingarg05** [mrdoob/three.js#14979]
The webcam example works OK on chrome, but does not work in Safari - both on iOS (12.0) or on Mac (Safari 11.1.2 on mac 10.13.6).

Unable to access the camera/webcam. TypeError: Type error

  https://threejs.org/examples/#webgl_materials_video_webcam

##### Browser

- [ ] All of them
- [ ] Chrome
- [ ] Firefox
- [x] Safari
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [ ] Windows
- [x] macOS
- [ ] Linux
- [ ] Android
- [x] iOS

**Comment by Mugen87** [comment]
It works with Chrome but not with Firefox and Safari. FF says: _Unable_ to access the camera/webcam. TypeError: "Argument 1 is not valid for any of the 1-argument overloads of URL.createObjectURL."_

It seems that the following line causes the error:
```js
video.src = window.URL.createObjectURL( stream );
```
So `URL.createObjectURL` does not seem to accept an object of type `MediaStream`.

**Comment by Mugen87** [comment]
@sachingarg05 Can you please change the above line to this code in the example and test if it solves the problem for you?
```
video.srcObject = stream;
```

**Comment by Mugen87** [comment]
The linked PR should fix the problem. There is also a test link in order to verify the fix.

**Comment by sachingarg05** [comment]
I tested with the test link. This fixes it for Safari on mac. But still doesn't work on iOS Safari.

**Comment by Mugen87** [comment]
@sachingarg05 Sry, I can't reproduce this since I don't have an iOS device at hand. Maybe you can have a look?

**Comment by sdarpeng** [comment]
@mrdoob Please check and fix this bug. It still doesn't work on iOS safari.

**Comment by sdarpeng** [comment]
not yet on Chrome/iOS
