### ISSUE TITLE
PCD loader does not work in Microsoft Edge

### ISSUE THREAD

**Issue by k0rzun1n** [mrdoob/three.js#16358]
PCD loader does not work in Microsoft Edge.
Works in Chrome.
![image](https://user-images.githubusercontent.com/9442435/56931482-97576980-6af9-11e9-92d3-cdb014a7ad7f.png)

**Comment by Mugen87** [comment]
Can you please check if this version is working on your system: 

https://raw.githack.com/Mugen87/three.js/dev29/examples/webgl_loader_pcd.html

**Comment by k0rzun1n** [comment]
Checked, different error.
![image](https://user-images.githubusercontent.com/9442435/56983008-071e3080-6b9c-11e9-9f92-b5a5e82eab8f.png)

**Comment by Mugen87** [comment]
Um, it seems the following line in `LoaderUtils.decodeText()` produces the runtime error:

https://github.com/mrdoob/three.js/blob/ba4069a20ac532b24d4007e959e86fd861feed04/src/loaders/LoaderUtils.js#L28

Just returning the variable `s` seems to solve the issue. 

@donmccurdy #12934 introduced the usage of `decodeURIComponent()` and `escape()`. However, when I remove the usage of `TextDecoder` from `LoaderUtils.decodeText()` so the alternative code path is always used, I see the same error with other loaders. In Chrome, `webgl_loader_ply` reports an `Uncaught URIError: URI malformed` which is essentially the same error reported in Edge. It seems the current fallback does not properly handle all use cases.

@k0rzun1n Can you please verify if https://threejs.org/examples/webgl_loader_ply.html throws the same error on your machine?

**Comment by k0rzun1n** [comment]
It does.
![image](https://user-images.githubusercontent.com/9442435/57037664-3fdc0980-6c71-11e9-9bbc-74f249423ac6.png)

**Comment by donmccurdy** [comment]
> #12934 introduced the usage of decodeURIComponent() and escape() ...

Hm. That patch avoids failures when the string contains multi-byte characters, but introduces failures here. It was never a great fix for the former, but I don't know of another... should we just surround this in a try/catch?

```js
try {

  return return decodeURIComponent( escape( s ) );

} catch ( e ) {

  console.warn( 'THREE.LoaderUtils: Lorem ipsum...', e );

  return s;

}
```

Alternative solutions for multi-byte characters would be welcome, but be aware that character-by-character iteration may have performance implications.

**Comment by mrdoob** [comment]
This could also be solved by waiting for the Chromium-based Edge...?

**Comment by k0rzun1n** [comment]
Can we still have some crutch for all the cave people that won't update?

**Comment by Mugen87** [comment]
> This could also be solved by waiting for the Chromium-based Edge...?

I think so. But adding a simple try/catch seems appropriate to me in order to make the current method more robust.

**Comment by Mugen87** [comment]
Ups, we totally missed  #13764 😅 

However, I think I vote for the try/catch solution since other loaders like `PLYLoader` will just work and do not need an enhancement.

**Comment by donmccurdy** [comment]
I prefer the try/catch over using an `isASCII` flag suggested in #13764. 👍

**Comment by k0rzun1n** [comment]
It still doesn't work though.
![image](https://user-images.githubusercontent.com/9442435/57288187-7501b500-70d2-11e9-8cba-1a385e550a7b.png)

**Comment by Mugen87** [comment]
The fix is not in production yet. Can you please try it with the `dev` version:

https://raw.githack.com/mrdoob/three.js/dev/examples/webgl_loader_pcd.html

**Comment by k0rzun1n** [comment]
SCRIPT5025: The URI to be decoded is not a valid encoding
![image](https://user-images.githubusercontent.com/9442435/57288550-1be65100-70d3-11e9-960b-4dc85e962921.png)

**Comment by Mugen87** [comment]
The build files were not updated yet, 81e184c73b29c1b07c8e9fc3904c5855a65d44ee

Please try it again.

**Comment by k0rzun1n** [comment]
Yeah, it works now. 
![image](https://user-images.githubusercontent.com/9442435/57308680-3d116680-7100-11e9-9952-bd1181e5c438.png)
