### ISSUE TITLE
Normals flipped on some parts of the mesh that have double sided materials

### ISSUE THREAD

**Issue by pushmatrix** [mrdoob/three.js#17804]
##### Description of the problem
Upgrading from 107 to 108, I've noticed that parts of my model now look like they have flipped normals. This only occurs with double sided materials.
See here: https://vaulted-jonquil.glitch.me/

This is what it should look like, with the pattern being indented on both wheels. That's how it was in 107
<img width="448" alt="Screen Shot 2019-10-23 at 3 51 35 PM" src="https://user-images.githubusercontent.com/190692/67428886-07c4dc00-f5ad-11e9-9d6c-fcb8baff21e8.png">

In 108 though one of the wheels has the pattern looking like it's popping out:
<img width="489" alt="Screen Shot 2019-10-23 at 3 51 27 PM" src="https://user-images.githubusercontent.com/190692/67428991-3a6ed480-f5ad-11e9-9bc6-323113665241.png">

##### Three.js version

- [x] r108

##### Browser

- [x] All of them

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by elalish** [comment]
@pushmatrix Can you confirm if this model does or does not supply its own tangents? I'm curious if this may be related to #11438.

**Comment by pushmatrix** [comment]
I don't believe it specifies its own tangents

**Comment by WestLangley** [comment]
Git bisect points to #17586 as the PR that initiated the problem if the mesh is double-sided and has negative scale X. That was in r.109, not r.108 however.

**Comment by pushmatrix** [comment]
Here's the test glb
[wheels.glb.zip](https://github.com/mrdoob/three.js/files/3767694/wheels.glb.zip)

**Comment by WestLangley** [comment]
From 3 years ago: https://github.com/mrdoob/three.js/issues/10331#issue-194807426

>Basically it seems that ... gl_FrontFace is not working properly with double sided materials on Adreno GPUs.

Is this _still_ an issue that we need to accommodate?

//

This model appears to render correctly on my machine if we remove the Adreno workaround in `normalmap_pars_fragment`:

```glsl
#ifdef DOUBLE_SIDED

	// Workaround for Adreno GPUs gl_FrontFacing bug. See #15850 and #10331

	bool frontFacing = dot( cross( S, T ), N ) > 0.0;

	mapN.xy *= ( float( frontFacing ) * 2.0 - 1.0 );

#else

	mapN.xy *= ( float( gl_FrontFacing ) * 2.0 - 1.0 );

#endif
```

**Comment by elalish** [comment]
Hmm, I remember reading that comment too; I think I came across it while looking at this bug, which was apparently fixed in r108 (at least upgrading fixed it for us): https://github.com/GoogleWebComponents/model-viewer/issues/740

Maybe it's related? FWIW, I have gotten some feedback about old Adreno GPUs, so apparently they're still fairly common.

**Comment by mrdoob** [comment]
Just to confirm, this still happens in `dev`:

<img width="1215" alt="Screen Shot 2019-10-25 at 4 06 51 PM" src="https://user-images.githubusercontent.com/97088/67609442-9d917000-f741-11e9-8469-d0f6c082a75e.png">

**Comment by WestLangley** [comment]
>Just to confirm, this still happens in dev:

Right. But not if you remove the Adreno bug workaround.

**Comment by Mugen87** [comment]
>  But not if you remove the Adreno bug workaround.

How about removing the workaround for now and then search for a different solution? The current implementation leads to wrong visuals no matter what platform you are using.

**Comment by WestLangley** [comment]
@Mugen87 In this particular case, I believe the geometries are mirrors of each other, but they share the same normal map.

**Comment by pushmatrix** [comment]
Inspecting the wheel model model, each wheel has its own UV shell. It doesn't share one.
And the vertex order is opposite.

However the face orientation is the same, at least in Blender.

<img width="1294" alt="Screen Shot 2019-11-18 at 11 21 05 AM" src="https://user-images.githubusercontent.com/190692/69070346-fc22d480-09f5-11ea-8239-7dc9abb9331f.png">

So I'm not sure whether it's a bug in r108, or if r108 is now doing things properly. ¯\_(ツ)_/¯

**Comment by mrdoob** [comment]
@pushmatrix can you compare with Unity or Blender?

**Comment by pushmatrix** [comment]
@mrdoob 

## Blender 2.8
<img width="866" alt="Screen Shot 2019-11-20 at 8 27 27 AM" src="https://user-images.githubusercontent.com/190692/69242806-abcf8200-0b6f-11ea-9884-1978964a2899.png">

## Unity
<img width="685" alt="Screen Shot 2019-11-20 at 8 40 30 AM" src="https://user-images.githubusercontent.com/190692/69243611-6f048a80-0b71-11ea-8a9c-895007ebf262.png">


## Sketchfab
<img width="626" alt="Screen Shot 2019-11-20 at 8 32 48 AM" src="https://user-images.githubusercontent.com/190692/69243124-5cd61c80-0b70-11ea-80e9-596d2303a7ed.png">

**Comment by mrdoob** [comment]
@pushmatrix 

Unity is hard to see because the light is in the same direction the camera is, but looks like Unity is wrong too? 🤔

**Comment by pushmatrix** [comment]
@mrdoob 

Yeah it does depend a bit on the lighting it ends up being an illusion and looking like it's popped up in some places. But when you rotate around, it disappears.


Here it is in other light, where it appears correct
<img width="265" alt="Screen Shot 2019-11-20 at 2 36 16 PM" src="https://user-images.githubusercontent.com/190692/69271688-4e552880-0ba3-11ea-834d-ba9a4d7c4ee5.png">

**Comment by WestLangley** [comment]
@mrdoob Front-faces have counter-clockwise winding order in three.js. Typically, the UVs of the 3 vertices of each face also have counter-clockwise winding order on the UV map.

In this example, my _conjecture_ is the model on the left has counter-clockwise UVs and the model on the right has _clockwise_ UVs. The model the right is rendering incorrectly in three.js when `doubleSide` is `true`.

AFAIK, removing the Adreno-workaround fixes the problem for non-Adreno GPUs.

**Comment by WestLangley** [comment]
@pushmatrix Your Unity example appears to have directional lights from two directions. That makes it difficult to discern what is going on. A single light may be preferable.

**Comment by pushmatrix** [comment]
@WestLangley I am using the same environment map the <model-viewer> is using, but likely it doesn't have the same rotation. I will try with a single light.

**Comment by pushmatrix** [comment]
@WestLangley Single directional light rotating around. I feel like I'm looking at an optical illusion

![unity](https://user-images.githubusercontent.com/190692/69273355-34691500-0ba6-11ea-99e9-fdf057770ccb.gif)

**Comment by pushmatrix** [comment]
Seems like Unity makes the grooves pop in and out depending on how the light hits it, but at least it's consistent for both.

Threejs is also consistent, but one definitely looks always popped out:
![wheels](https://user-images.githubusercontent.com/190692/69273688-d5f06680-0ba6-11ea-9d3a-2ce837b62618.gif)

**Comment by mrdoob** [comment]
I feel like there is something wrong in the Unity one. Like it needs something like. `material.normalMapScale.x = -1`.

**Comment by mrdoob** [comment]
@WestLangley 

> @mrdoob Front-faces have counter-clockwise winding order in three.js. Typically, the UVs of the 3 vertices of each face also have counter-clockwise winding order on the UV map.
>
> In this example, my _conjecture_ is the model on the left has counter-clockwise UVs and the model on the right has _clockwise_ UVs. The model the right is rendering incorrectly in three.js when `doubleSide` is `true`.
>
> AFAIK, removing the Adreno-workaround fixes the problem for non-Adreno GPUs.

Thanks, that makes sense. I think it still deserves more investigation though. If Sketchfab looks correct in all devices we may have to look at their shaders.

**Comment by Mugen87** [comment]
I had a look at the respective shader code today and it seems they are not using "Per-Pixel Tangent Space Normal Mapping".

According to this [post](https://help.sketchfab.com/hc/en-us/articles/211714583-Tangent-Space-and-Normal-Maps), Sketchfab expects tangent definitions in assets or these data are 
generate based on uv coordinates. That maps what I've seen in the GLSL code.

If I add tangents to the model via `BufferGeometryUtils.computeTangents()` and set `Material.vertexTangents` to `true`, the result seems fine:

![image](https://user-images.githubusercontent.com/12612165/69335879-e7e11080-0c5d-11ea-9dda-aec0410d3e18.png)


BTW: Is it okay to share their code snippets here^^? After all, it's not open-source.

**Comment by pushmatrix** [comment]
For consistency, here is Sketchfab with 1 directional light moving back and forth:

![sketchfab](https://user-images.githubusercontent.com/190692/69347801-23baac80-0c43-11ea-983c-5946535149b7.gif)

**Comment by WestLangley** [comment]
@pushmatrix Can you _please_ demonstrate that #17958 works for your model?

**Comment by WestLangley** [comment]
three.js computes tangents in the fragment shader. I believe it works correctly if a hack to accommodate certain buggy Adreno GPUs is removed. See #17958.

//

Sketchfab computes tangents on the CPU when tangents are required and are not provided by the model. (@donmccurdy This is what the glTF spec requires.)

three.js can do that too, but it will mean adding correct tangents to all built-in geometries. three.js will also have to implement the MIKKTSpace algorithm to replace `ComputeTangents()`. Since three.js supports both indexed and non-indexed geometries, I expect this will require considerable effort.

**Comment by pushmatrix** [comment]
Fixes it!
<img width="1143" alt="Screen Shot 2019-11-21 at 10 02 54 AM" src="https://user-images.githubusercontent.com/190692/69349676-28349480-0c46-11ea-8a31-adc5e7cbcfce.png">

**Comment by mrdoob** [comment]
Okay, so seems like the solution here is to revert the Adreno workaround (#17958) and recommend people to use `BufferGeometryUtils.computeTangents()` when the model doesn't have tangets and they're aiming to support Adreno GPUs (#15850).

Sounds good?

**Comment by mrdoob** [comment]
Another solution is to call `BufferGeometryUtils.computeTangents()` ourselves automatically when is not provided and remove all the code that computes tangents in the fragment shader... 🤔

**Comment by Mugen87** [comment]
`BufferGeometryUtils.computeTangents()` currently requires an index so it we can't use it in the core. However, it would be preferable if `three.js` could generate tangents according to MIKKTSpace at some point and then remove `perturbNormal2Arb()`.

**Comment by WestLangley** [comment]
@WestLangley wrote:

> it will mean adding correct tangents to all built-in geometries.

Changing my mind... Tangents are not necessarily required.  Instead, I would restore the method `BufferGeometry.computeTangents()` and "override" that method for all built-in geometries for which we can set exact tangents analytically.

//

>Another solution is to call BufferGeometryUtils.computeTangents() in the engine automatically when is not provided and remove all the code that computes tangents in the fragment shader...

That sounds right to me.

>BufferGeometryUtils.computeTangents() currently requires an index so it can't be use in the core. 

I think that is easily fixed. And it will have to be fixed to support https://github.com/mrdoob/three.js/issues/17804#issuecomment-557135610.

**Comment by donmccurdy** [comment]
> it would be preferable if three.js could generate tangents according to MIKKTSpace at some point and then remove perturbNormal2Arb()...

I don't know if MikkTSpace should necessarily replace the fragment shader computation. The shader has almost no performance cost, and works fine for a majority of models. Precomputing tangents has a per-vertex upfront cost every time, and no benefit except in these specific cases. 😕 Despite what the glTF spec says, I'm having a hard time justifying doing that by default.

It would be nice if `BufferGeometryUtils.computeTangents` could implement the MikkTSpace approach — that is the best algorithm, if you must precompute them. But it would probably be easier to put MikkTSpace in tools like glTF-Pipeline or gltfpack, which can use the existing native implementation, and do the calculation in advance, offline.

**Comment by mrdoob** [comment]
@donmccurdy 

But, say... in the `<model-viewer>` use case, I don't think there is a reliable way to know if the user has a Adreno GPU but we would want to look right (https://github.com/GoogleWebComponents/model-viewer/issues/740).

Should `<model-viewer>` (and others projects that want x-gpu support) call `BufferGeometryUtils.computeTangents` when tangents are not provided, or should Three?

**Comment by mrdoob** [comment]
@pushmatrix

Haha, I've just realized where these wheels are from 😁

https://bumbleride.com/products/era?variant=20719969599599

<img width="672" alt="Screen Shot 2019-11-22 at 3 52 19 PM" src="https://user-images.githubusercontent.com/97088/69463035-42529d80-0d40-11ea-894d-cd34a74c5168.png">

**Comment by pushmatrix** [comment]
@mrdoob 🕵

**Comment by mrdoob** [comment]
Okay then, lets revert the workaround for now.
