### ISSUE TITLE
XR: session events are incorrect or missing when using immersive-ar and multitouch

### ISSUE THREAD

**Issue by hybridherbst** [mrdoob/three.js#23574]
**Describe the bug**

It seems that something inside three's immersive session handling messes with the events that would be expected from the immersive session. In particular, when trying to use multitouch during an AR session, the expected order of events is

but when using threejs the order of events is

(only the first finger produces a selectstart and subsequent select and selectend events, but all fingers produce inputdevicechange events as expected).

To verify that this must indeed be a three issue and not a Chrome / immersive session bug, I reproduced this in both three and vanilla WebXR; vanilla WebXR has the expected order of events but three somehow "eats" the expected multitouch events from all but the first finger.

**To Reproduce**

Steps to reproduce the incorrect behavior (when using threejs):
1. connect Android phone to chrome://inspect
2. open on phone https://shine-jumpy-bass.glitch.me/ (to see the code go to https://glitch.com/edit/#!/shine-jumpy-bass)
3. open the page via chrome://inspect so you see logs
4. put one finger on the screen (keep it) - note "inputdevicechange" and "selectstart" events
5. lift finger - note "select", "selectend", "inputdevicechange"
6. put one finger down again
7. put second finger down - note only "inputdevicechange"
8. lift one finger - note no event at all
9. lift last finger - note "select", "selectend", "inputdevicechange"
10. try with more fingers, all but the first will only send "inputdevicechange"

Note that the first placed finger will send correct events, independent of the order of lifting fingers again.

![image](https://user-images.githubusercontent.com/2693840/155440244-782b7c07-e9de-4ccb-be17-c6308a5cb351.png)

Steps to reproduce the expected behavior (when using vanilla WebXR):
1. connect Android phone to chrome://inspect
2. open on phone https://xr-session-multitouch-crbug.glitch.me/ (to see the code go to https://glitch.com/edit/#!/xr-session-multitouch-crbug)
3. open the page via chrome://inspect so you see logs
4. put one finger on the screen (keep it) - note "inputdevicechange" and "selectstart" events
5. lift finger - note "select", "selectend", "inputdevicechange"
6. put one finger down again
7. put second finger down - note same order, "inputdevicechange" followed by "selectstart"
8. lift one finger - note "select", "selectend", "inputdevicechange"
9. lift last finger - note "select", "selectend", "inputdevicechange"

***Code***

```js
        session.addEventListener( 'select', onSessionEvent );
        session.addEventListener( 'selectstart', onSessionEvent );
        session.addEventListener( 'selectend', onSessionEvent );
        session.addEventListener( 'inputsourceschange', onInputSourcesChange );
       
...

      function onSessionEvent(event) {
          console.log("session event", event);
      }
      
      function onInputSourcesChange( event ) {
         console.log("input sources change", event); 
      }
```

***Live example***

* Incorrect events (threejs): https://shine-jumpy-bass.glitch.me/ (to see the code go to https://glitch.com/edit/#!/shine-jumpy-bass)
* Works as expected (vanilla WebXR): https://xr-session-multitouch-crbug.glitch.me/ (to see the code go to https://glitch.com/edit/#!/xr-session-multitouch-crbug)

**Expected behavior**

Correct event order from controller events in threejs.

**Platform:**

 - Device: [Mobile]
 - OS: [Android]
 - Browser: [Chrome, Firefox]

**Comment by hybridherbst** [comment]
For reference, I think this is one of two issues currently preventing/breaking multitouch usage in immersive sessions.

The other one (regarding assignment of sources to controllers) is https://github.com/mrdoob/three.js/issues/23187 which would be fixed by https://github.com/mrdoob/three.js/pull/23188.

**Comment by mrdoob** [comment]
Is this fixed now?

**Comment by hybridherbst** [comment]
I just updated https://glitch.com/edit/#!/shine-jumpy-bass to always use the latest dev build;
unfortunately the steps above still reproduce (with vanilla JS producing correct events and three.js producting incorrect events).

This one only concerns with the assignment of events to fingers/controllers, but can't work around the underlaying issue with events being missing:
- #23188

For Needle Engine we had to work around this by manually dispatching the missing events, but that is only bandaid...
