### ISSUE TITLE
r152 multiple UV mapping bug

### ISSUE THREAD

**Issue by RemusMar** [mrdoob/three.js#25946]
### Description

@mrdoob @donmccurdy @Mugen87 
Guys, I'm not a big fan of the r152 changes (is never a good idea to change the default values for "something"), but let's ignore that.
There is a big issue in r152 (and maybe r151 as well) related to a material with multiple UV Mappings.
In r152 is used the same UV mapping for all the texture layers.

Screenshots:
r150 (good):
![150](https://user-images.githubusercontent.com/11772787/234917718-3781c8e4-c0ee-44b7-8b22-42e4d9bef06c.png)

r152 (bad):
![152](https://user-images.githubusercontent.com/11772787/234917786-12349006-2a5d-4303-b159-1f5abf547048.png)

### Reproduction steps

r150 = good
r152 = bad

### Code

// I'm sure you are aware of the code changes

### Live example

r150 (good):
https://necromanthus.com/Test/html5/SMC.html 

### Version

152

### Device

Desktop, Mobile

### Browser

Chrome, Firefox, Safari, Edge

### OS

Windows

**Comment by mrdoob** [comment]
It's probably this change: https://github.com/mrdoob/three.js/pull/25943

**Comment by RemusMar** [comment]
> It's probably this change: #25943

The GLTF ids are not correct anyway.
If the first one is "uv", the second one cannot be "uv1".

**Comment by Mugen87** [comment]
The following is a pure objective analysis: 

Unfortunately, the SEA3D library you are using is not compatible to `r152`. The respective loader produces a file with `uv` and `uv2` which means it does not honor the latest uv naming conventions. As long as the SEA3D loader isn't updated, you have to change the `uv` attributes by yourself.

Regarding https://github.com/mrdoob/three.js/pull/25943#issuecomment-1525025928, I have to admit the situation is not ideal that we can't provide any sort of backwards compatibility. But as mentioned in the comment, the potential side effects of the fallback are not clear to me, too. 

@RemusMar Can you please at least test if renaming the `uv2` attribute to `uv2` fixes the issue. I know you are not happy with that but it's important to know whether this fixes the issue or not.

**Comment by donmccurdy** [comment]
> The respective loader produces a file with uv and uv2...

this is technically still ok, right? as long as texture.channel=2 is specified (or can be inferred?).

**Comment by RemusMar** [comment]
> Can you please test if renaming the uv2 attribute to uv1 fixes the issue.

Michael, that's that 1st thing I did after Ricardo's response.
The same wrong result in r152.
And the situation is even worse:
I get the same wrong result in r152 even with the GLTF version (here is the good 150 one):
https://necromanthus.com/Test/html5/SMC_gltf.html

**Comment by bhouston** [comment]
I am running into glTF files exported from blender 3.5.1 (the latest) are no longer loaded in Three.js after updating to the latest Three.js.

<img width="829" alt="Screenshot 2023-04-27 at 4 05 14 PM" src="https://user-images.githubusercontent.com/588541/234978685-ac71f9e5-c71c-4cd1-9601-fdab0f18a1a2.png">

The issue is the second UV map is used for AO.  Here is the Blender shader graph section that is causing the issue:

<img width="1600" alt="Screenshot 2023-04-27 at 4 08 46 PM" src="https://user-images.githubusercontent.com/588541/234979386-87fe0b66-818e-43da-8c36-28c6d9a51334.png">

**Comment by bhouston** [comment]
I can confirm it loads properly with 0.150 and 0.151, but not with 0.152.  So I will just stick with the older version for now.

**Comment by mrdoob** [comment]
@bhouston can you share I've if those files?

**Comment by mrdoob** [comment]
@donmccurdy 

> this is technically still ok, right? as long as texture.channel=2 is specified (or can be inferred?).

That's right yeah.

@sunag would it be possible to update `SEA3DLoader` with support for `texture.channel`?

**Comment by sunag** [comment]
@RemusMar I believe that renaming the string `uv2` to `uv1` in this line should solve it:

https://github.com/sunag/sea3d/blob/0533fb0e1192915a50f2d0c38d7570d64dc37be2/Source/Three.JS/SEA3DLoader.js#L1899

**Comment by sunag** [comment]
And added `mat.lightMap.channel = 1` here.

https://github.com/sunag/sea3d/blob/0533fb0e1192915a50f2d0c38d7570d64dc37be2/Source/Three.JS/SEA3DLoader.js#L2758

**Comment by RemusMar** [comment]
> I believe that renaming the string uv2 to uv1 in this line should solve it

I did that in the first place and it didn't change anything.

> And add mat.lightMap.channel = 1 or mat.aoMap.channel = 1 here

Yes, that did the trick.
Well done!

But guys, we still have a big problem.
This GLB (GLTF) sample still gives wrong results in r152:
https://necromanthus.com/Test/html5/SMC_gltf.html 
Did you make any change in the GLTF loader in r151 or r152 (related to multiple UV mapping)?

**Comment by mrdoob** [comment]
Yes, make sure you're using the latest version of the library and also the latest version of `GLTFLoader`.

**Comment by RemusMar** [comment]
> Yes, make sure you're using the latest version of the library and also the latest version of GLTFLoader.

Everything updated to r152bis
All good now.
152 SEA3D: https://necromanthus.com/Test/html5/SMC.html
152 GLTF: https://necromanthus.com/Test/html5/SMC_gltf.html

**Comment by bhouston** [comment]
I think the issue I was running into was a mismatch between the version of glTF loader and the rest of the Three.js.  This is caused by the stdlib-threejs not being in sync with Three.js over on the React-Three/Fiber project - thank you @CodyJasonBennett: https://github.com/pmndrs/three-stdlib/pull/226

**Comment by RemusMar** [comment]
> I think the issue I was running into was a mismatch between the version of glTF loader and the rest of the Three.js

Yes Ben, it was the same issue for me with the GLB sample.
As I said before, all good now.

**Comment by makc** [comment]
@bhouston after all that talk how npm can keep versioning in check 🥲
