### ISSUE TITLE
E2E tests broken.

### ISSUE THREAD

**Issue by Mugen87** [mrdoob/three.js#28296]
### Description

Since about two weeks the E2E testing as a part of the CI is broken. Jobs fails with the following error:

> Run actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808
With the provided path, there will be 153 files uploaded
Artifact name is valid!
Root directory input is valid!
Error: Failed to CreateArtifact: Received non-retryable error: Failed request: (409) Conflict: an artifact with this name already exists on the workflow run

AFAIK, we have not recently changed the CI settings apart from the updates renovate performs.

I have temporarily removed the E2E jobs from the CI via https://github.com/mrdoob/three.js/commit/7604fee89cedf7ba358c1c452bccf12345027034. 

### Reproduction steps

-

### Code

-

### Live example

-

### Version

r164

**Comment by Mugen87** [comment]
BTW: This is one of the first PRs with broken E2E tests: https://github.com/mrdoob/three.js/pull/28226

The first breakage also occurred _before_ the demos were migrated to `setAnimationLoop()` so I don't think the E2E problems are related on latest changes to the example code base.

**Comment by ycw** [comment]
culprit https://github.com/mrdoob/three.js/pull/28175

**Comment by Mugen87** [comment]
I'll revert https://github.com/mrdoob/three.js/pull/28229 and see if it helps.

**Comment by Mugen87** [comment]
Done! But I believe existing PRs must rebase otherwise they don't get the updated configuration file.

**Comment by ycw** [comment]
still no luck https://github.com/mrdoob/three.js/actions/runs/8972633808/job/24641039564?pr=28287 :(

**Comment by Mugen87** [comment]
So it seems we have to apply a migration task so v4 of `actions/upload-artifact` works. I'll give it a try:

https://github.com/mrdoob/three.js/commit/37e1cb53c2e6abbd603539263eadb21483c51366

**Comment by Mugen87** [comment]
Um, it seems the upload works again but I can't regenerate the example screenshots correctly. I've tried it on two systems (macOS and Windows) but many examples still fail during the CI.

@ycw Would you mind helping and file a PR like #28301? Meaning run `npm run make-screenshot` locally and add the new screenshots to a commit? Maybe it works on your system...

**Comment by ycw** [comment]
all or some? there're only 70 images in #28301, what are they?

**Comment by ycw** [comment]
ok, lets do it

**Comment by ycw** [comment]
done.

**Comment by ycw** [comment]
I notice that all animation-related screenshots made in #28306 lags behind the old ones by few frames

and this one is totally blank: [examples/screenshots/webgl_animation_skinning_additive_blending.jpg](https://github.com/mrdoob/three.js/pull/28306/files#diff-3c38c1bc0be5906c1813fe15d8b081ba5dc457a7b2542cd93c1e9e7243c6e29d)

🤔

**Comment by Mugen87** [comment]
see https://github.com/mrdoob/three.js/pull/28306#issuecomment-2098156986.

When using `setAnimationLoop()`, the scene is not immediately rendered compared to previous call of `animate()`. I suspect the E2E tests are not fully compatible with the new approach. 

If the timing of the tests would be 100% deterministic, screenshot generation should always produce the same result (maybe with very minor diff).

**Comment by RemusMar** [comment]
> When using setAnimationLoop(), the scene is not immediately rendered compared to previous call of animate().

It's even worse.
For the first 100-200ms all the scene animations are out of sync.
They start with very high speed and reach the correct 60FPS after 100-200ms.
I've updated all my samples to use `setAnimationLoop()` but I dislike this behaviour.

**Comment by Mugen87** [comment]
@RemusMar Can you try to compute a delta time not via `Clock` but like so:
```js
function animate( time ) {

    const delta = ( time - prevTime ) / 1000;
    prevTime = time;
```
Would this solve the problem on your side? I'm asking since maybe we could add a `delta` time value to the signature of `animate()`.

**Comment by RemusMar** [comment]
To summarize:
The browser/monitor are always in sync when using `requestAnimationFrame( animate );`
But they are not in sync for the first 100-200ms when using `renderer.setAnimationLoop( animate );`

**Comment by RemusMar** [comment]
> Expected because first animate frame is ... scheduled ... by setAnimationLoop()

That's true.
And here we need to find a solution or workaround.

**Comment by Mugen87** [comment]
Instead of directly rendering the first frame, the engine let the browser decide when to schedule the first one. If apps need a different behavior, they can always call their animate function right away after the init routine. That would be the workaround you are asking for.

**Comment by RemusMar** [comment]
> Instead of directly rendering the first frame, the engine let the browser decide when to schedule the first one. If apps need a different behavior, they can always call their animate function right away after the init routine. That would be the workaround you are asking for.

In my opinion the current logic for `renderer.setAnimationLoop( animate )` is not correct.
And you cannot expect to modify thousands of samples just to correct that.

**Comment by Mugen87** [comment]
Please do not hijack this issue to discuss the logic of `setAnimationLoop()`. This issue is about fixing the E2E tests.

Besides, using `setAnimationLoop()` is not mandatory, you can keep managing the animation loop on app level if you want.

**Comment by RemusMar** [comment]
> This issue is about fixing the E2E tests.

It's much more than that Michael.
Anyway, I won't "bother" you anymore.
good luck

**Comment by trusktr** [comment]
> If the timing of the tests would be 100% deterministic

This is easy to do by replacing `window.requestAnimationFrame` with a custom one along with a new `nextFrame(time)` function that ticks it.

**Comment by mrdoob** [comment]
@Mugen87 I think it may be best to revert all the `setAnimationLoop ()` PRs... 😕

**Comment by Mugen87** [comment]
And what do we do when we start migrating the examples to `WebGPURenderer`? Should we remove the usage of `setAnimationLoop()` there as well?

To me, letting the renderer handle the animation loop is better what we have before. It opens up interesting options like automatic time computations or node related internal update mechanism. We essentially loose that if we ask the app to manage the animation loop again.

If we can't fix the E2E tests, would it also be an option to remove E2E testing from the CI? We can still use the logic to generate screenshots for the website.

**Comment by Mugen87** [comment]
In any event, I've filed #28322 to see if it solves the E2E issues.
