### ISSUE TITLE
WebGPURenderer Performance Significantly Lower Than WebGLRenderer

### ISSUE THREAD

**Issue by tenkkov** [mrdoob/three.js#30560]
### Description

**Summary**

When switching from WebGLRenderer to WebGPURenderer, I experience a significant drop in performance. The same scene, containing thousands of non-instanced meshes, runs smoothly at 60 FPS on WebGL but drops to 15 FPS on WebGPU, a 4x decrease in performance.

**Expected Behavior**

WebGPURenderer should provide comparable or better performance than WebGLRenderer, given its modern API and intended improvements over WebGL.

**Current Behavior**

Rendering 20,000 non-instanced basic cube meshes:

WebGLRenderer: ~60 FPS on Mac (Apple Silicon M1 Pro)

WebGPURenderer: ~15 FPS (4x slower)

No errors or warnings appear in the Chrome console.

### Reproduction steps

1. Create a Three.js scene with 20,000 Mesh instances.
2. Use WebGLRenderer and observe smooth 60 FPS performance.
3. Switch to WebGPURenderer by uncommenting the renderer swap.
4. Observe FPS dropping significantly (down to 15 FPS).

### Code

see live example below

### Live example

https://jsfiddle.net/15zfestk/1/

### Version

r.0.173.0

### Device

Desktop

### Browser

Chrome

### OS

MacOS

**Comment by Mugen87** [comment]
Some more context: https://discourse.threejs.org/t/why-webgpurenderer-performance-significantly-lower-than-webglrenderer/77629/9

**Comment by Mugen87** [comment]
To further explain the major performance gap: This is how `WebGLRenderer` renders the scene when four cubes are configured:

<img width="1023" alt="Image" src="https://github.com/user-attachments/assets/f7bbbbff-e2b6-47e3-8625-ed17dfe0467a" />

`WebGPURenderer` does this:

<img width="1021" alt="Image" src="https://github.com/user-attachments/assets/3914858c-d367-4c8a-a2ed-8e86831c4e4e" />

As you can see, there is a considerable amount of state changes during each draw command. Many scenes won't have an issue with this because the number of render objects is low. But the more render objects you have in a scene, the sooner `WebGPURenderer` get CPU limited. 

#30562 fixes the VAO related issues but they are unfortunately negligible compared to the UBO related overhead. I guess we need a different approach in the renderer to minimize these state changes. 

Would be a single UBO for all object scope uniforms a potential solution?

**Comment by RenaudRohlinger** [comment]
Nice catch with the VAO!

Related (I like the CommonUniformBuffer interface):
https://github.com/mrdoob/three.js/pull/27388

Unless we implement a pool system I don't think we can use a single UBO for all object-scope uniforms as a potential solution since we'd be very limited by the number of meshes. With a typical 16KB max block size and each mat4 taking 64 bytes in std140, that limits us to about 256 meshes.

**Comment by Mugen87** [comment]
Good to know that. I hope we can revisit https://github.com/mrdoob/three.js/pull/27388 soon.

**Comment by CodyJasonBennett** [comment]
> With a typical 16KB max block size

This is the limitation per draw call as guaranteed by the WebGL 2 specification. You can have a larger buffer bound and adjust the offset dynamically. I've shared many words of this and scheduling in general, but I'm not sure they've been heard, reading this.

**Comment by aardgoose** [comment]
Can this issue be clarified, is it performance with the webGL fallback backend that the OP has an issue with or the WebGPU backend or both?

Re #27388, I'll revisit it in a few weeks time, I recall looking at applying a similar mechanism to the WebGL fallback, but found that rather more complicated because of the different api styles, although I'd have to check.

**Comment by Mugen87** [comment]
> . You can have a larger buffer bound and adjust the offset dynamically.

When I understand the spec correctly, you can use `gl.bindBufferRange()` in WebGL 2 for that purpose.

https://registry.khronos.org/OpenGL-Refpages/es3.0/html/glBindBufferRange.xhtml

In WebGPU, it should be the `dynamicOffsets` parameter of `setBindGroup()`.

https://www.w3.org/TR/webgpu/#gpubindingcommandsmixin-setbindgroup

It seems both APIs are not used in #27388 yet.

**Comment by sunag** [comment]
@mrdoob @Mugen87 My apologies for the delay. I'm currently dealing with a health issue, but I will look into it as soon as I recover.

**Comment by aardgoose** [comment]
#27388 only applies to webGPU, the dynamicOffsets isn't really useful in the current renderer AFAICS. The offset in createBindGroup is all that is required to use a single buffer.

The issue with webGL is that the buffer updates and draw calls are interleaved and executed in a single pass, whereas the webGPU renderer updates the arrayBuffer and queues the draw calls  for later execution, this allows the single buffer update to be inserted before the queued draw calls are executed.  

For a WebGL solution you need to have two passes through the render list.

1. pass 1: Update the intermediate arrayBuffers only.
2. write the gl buffer.
3. pass 2: draw calls.

This doesn't match the current code structure.

**Comment by Spiri0** [comment]
I don't know if this is related to this point or if it is a separate topic. Since r173 I have noticed a frame drop (WebGPURenderer). Suddenly the frame rate drops from 120 fps to 30 fps. Since I haven't changed anything in the app itself, just the threejs release from r172 to r173 and now r174, I keep noticing this. There is no error message, which makes the analysis more difficult. The app runs at 120 fps and suddenly it drops to 30 fps. Sporadically it peaks back to 120fps. Since I'm not allocating any new buffers or new geometries, that's strange. Since up until r172 it always ran at 120fps, something must have happened from r172 to r173.

**Comment by RenaudRohlinger** [comment]
@Spiri0 I noticed similar issue on Windows after r172, the issue was caused by a memory leak, and should be fixed with https://github.com/mrdoob/three.js/pull/30647

**Comment by Spiri0** [comment]
@RenaudRohlinger Your extension seems to make the frame drop less frequent. I was curious and implemented it in my apps. But the frame drop still occurs. An interesting phenomenon.

Both times I just started the app and nothing else. But in the first picture you can see a constant 120fps, which was always the normal case

<img src="https://github.com/user-attachments/assets/0743489f-f2cd-4af4-bf8b-6f85530dd86d" width="300">
<img src="https://github.com/user-attachments/assets/38d20d98-6555-46c5-b847-006d718c0215" width="300">

In the second screenshot, threejs seems to fall into something like a safe mode with 30fps.
There are no error messages. Even stranger, as soon as I open the console it suddenly jumps to 120fps. As you can see, the render loops are very fast, less than a millisecond. So Threejs and the app are very much in the green zone in terms of performance.

<img src="https://github.com/user-attachments/assets/458ac140-baf6-46db-a086-e9b8c23bd580" width="300">

It's definitely an improvement, because now it jump from 30fps to 120fps instead from 120fps to 30fps. I've tested opening the console several times and so far with your extension it always triggers the jump from the faulty 30fps to 120fps. That's very good because it proves that your expansion is on the right track.

**Comment by RenaudRohlinger** [comment]
Thanks @Spiri0! Could you try this on different web browser that supports well WebGPU (Chrome Canary, Chrome Beta, Edge) and potentially a different device to confirm that's more on the threejs side rather than how it interact with your browser/GPU?

Also to know your GPU model would greatly help.

**Comment by Spiri0** [comment]
Good point. I use slimJet because Chrome on Linux had limited WebGPU support for some time. But with the current version of Chrome it's working normally again. Then slimJet is the cause. I tested it again with maximum WebGPU limits and with the latest Chrome it runs at 120fps again. That's reassuring. 
I have an ATI Readon XTX7900. What I do runs at 120fps even if I push threejs to the maximum limits of my GPU. This means that threejs has already implemented WebGPU very well

**Comment by jellychen** [comment]
I'm also encountering a similar issue. Are there any future plans or optimization goals for this problem?

**Comment by sunag** [comment]
> Are there any future plans or optimization goals for this problem?

I have plans to work on it this month, after solve [this](https://github.com/mrdoob/three.js/pull/31059#issuecomment-2860882752) issue I will check it out.

**Comment by Spiri0** [comment]
I update large quantities of uniforms with the WebGPURenderer without any problems. However, I do this manually with storage buffers. With these, I can selectively update thousands of uniforms very efficiently on the CPU side. I've implemented something like this privately (#27388). I believe this issue is about this topic.

**Comment by jellychen** [comment]
Are there any recent developments? The current performance of WebGPU remains the biggest hurdle for our migration.

**Comment by sunag** [comment]
> Are there any recent developments? The current performance of WebGPU remains the biggest hurdle for our migration.

@jellychen I would just like to ask for your patience, repetitive questions do not solve anything, and this is not the only task we have, we have many more demands than people working on them.

**Comment by Spiri0** [comment]
> Are there any recent developments? The current performance of WebGPU remains the biggest hurdle for our migration.

You can hire me, and I'll solve your problem.
It's already possible to handle it with the WebGPURenderer

**Comment by jellychen** [comment]
> > Are there any recent developments? The current performance of WebGPU remains the biggest hurdle for our migration.
> 
> [@jellychen](https://github.com/jellychen) I would just like to ask for your patience, repetitive questions do not solve anything, and this is not the only task we have, we have many more demands than people working on them.

I'm really sorry for my lack of patience. We have some projects that are currently stuck at this point. Hopefully, we can get through this smoothly.

**Comment by Mugen87** [comment]
@greggman Hi again 👋 . I would like to ask for advice regarding this issue. 

Context: In `WebGLRenderer`, we did not use UBOs in our material system. Uniforms were individually updated via `uniform[1234][fi][v]()` or `uniformMatrix[234]fv()`. In `WebGPURenderer`, we have introduced UBO usage since it is required for WebGPU anyway and we wanted to use the same approach for the WebGL backend as well.

Currently we have shared UBOs for certain data (like camera uniforms) but separate UBOs for each object to maintain the object-scope uniform data (e.g. the world matrix). It turned out that with many render objects, this approach performs way worse than directly updating individual uniforms via e.g `uniform[1234][fi][v]()`. The performance difference is so large that it's obvious we don't use UBOs as intended.

How would you organize object-scoped data with UBOs? Is the idea to have a single large buffer holding the data and just bind a specific range for each draw call (as suggested in https://github.com/mrdoob/three.js/issues/30560#issuecomment-2675082155)? Or are UBOs in general a bad choice for fine-granular data that change per render call? I've heard of developers complaining about UBO usage because of that particular issue. At least in one documented case, the developer abandoned the usage and went back to individual uniform updates since they were faster overall (see https://github.com/mrdoob/three.js/issues/13700#issuecomment-376859354). Even faster than having a single large UBO.

Unfortunately, that is not an option we can use with WebGPU so we need an optimized solution with UBOs.

**Comment by Spiri0** [comment]
Here are two links that show how well Three WebGPU works. These were my prototype apps from over a year ago. I selectively update specific areas within the SBO's ( from CPU side ). Threejs uses exactly the right WebGPU tools to handle this efficiently. Don't worry about the licensing stuff. It's just to point out that decompilation is not permitted.

https://the-mars-project-app.site/local_map_viewer_v3/
https://the-mars-project-app.site/local_map_viewer_v4/

Use wasd, arrow keys and Space for movement. I don't have collision detection in these old examples.
The apps load new areas as you move around, and this datas and its associated metadatas then need to be efficiently sent to the GPU from the CPU. Doing this with traditional uniforms and textures would be cumbersome.
One must be aware that WebGPU is a different world and in many things there is no 1:1 analogy to WebGL.
The two examples are intentionally kept somewhat simple, as I've also used more structured surfaces and advanced techniques today.
I understand the desire to do things in the familiar way one is used to from WebGL. But if WebGPU were designed to be analogous to WebGL, then WebGPU wouldn't have been necessary, because WebGL could simply have further developed. These two examples demonstrate that Three.WebGPU can very efficiently transfer larger amounts of datas from the CPU to the GPU in each frame. Furthermore, the structs allow for clean clustering. I admit this isn't as straightforward as using simple uniforms in WebGL, but I couldn't have achieved this with WebGL. This is only possible with the WebGPU tools in Three.WebGPU.
From my perspective, there is no issue here.

**Comment by Mugen87** [comment]
> From my perspective, there is no issue here.

Unfortunately, there is. It is definitely an issue when developers migrate to `WebGPURenderer` and experience noticeable performance degradation in their apps. It is completely valid to have many individual render items in your scene and the renderer must handle this in a performant fashion. The current UBO implementation does not do that.

I would appreciate if this issue is not misused to demonstrate how performant certain apps have been implemented with WebGPU. Let's focus on how to correctly use UBOs with many individual render objects and different per-object uniform data.

**Comment by greggman** [comment]
I don't know if I can give three.js specific advice. 

For WebGPU there are some experiments [here](https://webgpufundamentals.org/webgpu/lessons/webgpu-optimization.html). 

The short version was, try to allocate one or more larger buffers for all UBOs, update all objects, do one upload per buffer (instead of one per object). There's examples of using `device.queue.writeBuffer` to update the buffers and `buffer.mapAsync`. On M1 Mac they both appear to perform about the same. M1 Mac is UMA (Unified Memory Architecture) so I'd expect different results on a PC with an AMD or NVidia GPU. I don't have access to my PC right now so I can't check.

Otherwise:

* putting vertex data in 1 buffer per object is better than 1 buffer per attribute as it's one call to `setVertexBuffer`
* separating uniforms into global, per material, per object is probably a good idea.

In my tests, WebGPU was significantly faster than WebGL

### M1 Mac

| technique | result |
| :-------- | :----- |
| [WebGL using gl.uniform](https://webgpufundamentals.org/webgpu/webgl-optimization-none.html) | 6000 cubes at 120fps |
| [WebGL using UBOs in one large buffer](https://webgpufundamentals.org/webgpu/webgl-optimization-uniform-buffers-one-large.html) | 3000 cubes at 120fps |
| [WebGPU using one large buffer w/WriteBuffer](https://webgpufundamentals.org/webgpu/webgpu-optimization-step5-use-buffer-offsets.html) | 15000 cubes at 120fps |
| [WebGPU using 2 large mapped buffers](https://webgpufundamentals.org/webgpu/webgpu-optimization-step6-use-mapped-buffers.html) | 14000 cubes at 120fps |

It's disappointing that WebGL is slow with UBOs in Chrome. Checking Firefox I got 5000 cubes using `gl.uniform` and 4500 using UBOs so maybe there is room for improvement in ANGLE in Chrome for UBOs.

**Comment by Spiri0** [comment]
> > From my perspective, there is no issue here.
> 
> Unfortunately, there is. 


Then I apologize. I tend to take alternative paths. I'm doing exactly what you want with the UBOs but with the SBOs.

**Comment by greggman** [comment]
I should add, there are other optimizations you can make, but I don't know which ones are appropriate for three.js

There's [Brandon's example of doing frustum culling on the GPU](https://toji.dev/webgpu-best-practices/render-bundles). I'm told that most AAA game engines use this type of technique. But, game engines are often not generic. They design around the engine rather than support every possible use case.

Another thing you can potentially do is use storage buffers. Storage buffers can be larger and more flexible than uniform buffers. So for example, if every object to be drawn uses the same `struct` then you can make an array of those structs 

```wgsl
@group(0) @binding(0) var<storage> perObjectData: array<PerObjectData>;
```

You can then select which per object data in the array by a single index, for example `instance_index` which you can pass in in `drawXXX`. Example

```js
// pseudo code

// draw 1 object and set `instance_index` to `someCubeInstanceIndex`
pass.setVertexBuffer(0, cubeVertexBuffer);
pass.draw(numCubeVertices, 1, 0, someCubeInstanceIndex); 

// draw 1 object and set `instance_index` to `someSphereInstanceIndex`
pass.setVertexBuffer(0, sphereVertexBuffer);
pass.draw(numSphereVertices, 1, 0, someSphereInstanceIndex);

// draw 1 object and set `instance_index` to `someSuzanneInstanceIndex`
pass.setVertexBuffer(0, suzanneVertexBuffer);
pass.draw(numSuzanneVertices, 1, 0, someSuzanneInstanceIndex);
...
```

in WGSL

```wgsl
// pseudo code

struct PerObjectData {
  ...
};

struct Interop {
  @builtin(position) pos: vec4f,
  @location(0) @interpolate(flat, either) instance_index: u32,
  ...
};

@group(0) @binding(0) var<storage> perObjectData: array<PerObjectData>;

@vertex fn vs(@builtin(instance_index) instance_index: u32) -> Interop {
  let objData = perObjectData[instance_index];
  
  ...
  return Interop(pos, instance_index, ...);
}

@fragment fn fs(v: Interop) -> @location(0) vec4f {
  let objData = perObjectData[v.instance_index];
  ...
  return color;
}
```

Again, many games do this kind of thing but they do it by requiring all objects to use the same struct and/or the same pipeline. Even without the same pipeline you can make a struct that is the union of all needed properties.  This gets more useful with [bindless](https://github.com/gpuweb/gpuweb/issues/380) since you can bind all the textures needed for all objects at once. Bindless support is probably at least year away though

**Comment by Mugen87** [comment]
After some more investigations I think we can use #27388 as a starting point. However, to make this work with WebGL as well we need to refactor the renderer a bit.

- After preparing the render lists and before start processing the render items, the nodes must be build for reach render item. This will automatically define the related uniforms which allows the engine to organize the object-scope uniforms into single buffers. So we need an additional iteration over the render lists for building the nodes. Or we do this right when the render item is pushed into the render list.
- @greggman I don't fully understand the size restriction yet. Does the 64KB in WebGPU restrict the overall size of the buffer or just the portion you can bind? Is there a similar size restriction for WebGL 2? I understand there is `MAX_UNIFORM_BLOCK_SIZE` and this does indeed just restrict the amount of memory you can bind and not the buffer itself.
- When the buffers are prepared, they are updated once via `writeBuffer()` in WebGPU and `bufferData()` in WebGL before start rendering.
- Then we use `GPUBufferBinding` in WebGPU for describing the bind group entry for `createBindGroup()`. This allows to define an offset into the large shared UBO so we process the relevant data for the draw command. The same is true for `bindBufferRange()` in WebGL 2.

Does that sound good as a first step to optimize the UBO usage?

**Comment by greggman** [comment]
You can use a buffer larger than 64k for uniforms. You just have to set the size of the portion you're using to 64k or less

```js
  const uniformBuffer = device.createBuffer({
     size: 2 * 1024 * 1024, // 2meg
     usage: GPUBufferUsage.UNIFORM,
  });
  const bindGroup = device.createBindGroup({                            //  +-- set the size
    layout: pipeline.getBindGroupLayout(0),                             //  |
    entries: [                                                          //  V
      { binding: 0, resource: { buffer: uniformBuffer, offset: someOffset, size: 65536 } },
    ],
  });
```

[working example](https://jsgist.org/?src=a6c1f2ae87522d18b17e3e01dc9450ab)

**Comment by sunag** [comment]
> After preparing the render lists and before start processing the render items, the nodes must be build for reach render item...

I drafted this 5 months ago, I'll see a way to clean up to merge. https://github.com/sunag/three.js/commit/2f76856a48d4fb29d385d890a5093a716f58ba5e

**Comment by Mugen87** [comment]
@greggman Understood! Thanks for the feedback! 👍 

When I understand the specs correctly, 64KB is a size limit in WebGPU which is equal on all platforms. With WebGL 2, we would have to query `MAX_UNIFORM_BLOCK_SIZE` and use the returned value. Is that correct?

Is there a minimum guaranteed size in WebGL2 that we could rely on? The spec (https://registry.khronos.org/webgl/specs/latest/2.0/) is not clear about that but I have read 16KB should be a save baseline. 64KB isn't supported on all platforms (see https://groups.google.com/g/webgl-dev-list/c/iOhFSs_YsrM).

**Comment by greggman** [comment]
The minimum `MAX_UNIFORM_BLOCK_SIZE` on WebGL2 is 16k. [It's in the spec](https://registry.khronos.org/OpenGL/specs/es/3.0/es_spec_3.0.pdf). Search for "MAX UNIF" instead of "MAX_UNIF" (space instead of underscore).

**Comment by greggman** [comment]
Just FYI, I don't know what system you're testing on but I [filed a bug to look into WebGL2 UBO perf](https://issues.angleproject.org/issues/459088194) and they found WebGL2 UBOs are up to 2x faster then `gl.uniform` on Linux using the examples linked in the issue. Again, I don't have access to my Windows machine at the moment but it would be good to test Windows Intel, Windows AMD, Windows NVidia to see how it goes and to check if the perf issue with UBOs is Metal only.

**Comment by Mugen87** [comment]
I'm testing on macOS. The OP has also used a macOS system.

I did some additional performance measurements for https://github.com/mrdoob/three.js/issues/32675#issuecomment-3714076306 and noticed something related to this issue. Thanks to our new `Object3D.static` property, we can bypass some internal checks and any UBO updates and only execute the bind in each frame.

WebGPURenderer with WebGL 2 backend (UBO): https://jsfiddle.net/gc38m7u6/
WebGLRenderer (no UBO): https://jsfiddle.net/angd4ws8/1/

With Chrome the WebGPURenderer/UBO demo runs around 12 FPS whereas the WebGLRenderer/UBO demo runs as 60 FPS. In Firefox the difference is less severe 28 FPS vs 60 FPS.

I did also a quick test with Chrome/Android (Pixel 8a) and it's 19 vs 57 FPS.

The performance analysis shows most time is spend with `gl.bindBufferBase()`.

<img width="382" height="101" alt="Image" src="https://github.com/user-attachments/assets/2e00d648-b14a-4e52-a31d-c4c65087fab9" />

<img width="488" height="232" alt="Image" src="https://github.com/user-attachments/assets/8413f98c-d03b-477c-9cde-1879c2be1d6b" />

So even if we use the single UBO approach, we still have to bind the UBO for each object which has a large hit on performance. 

You have mentioned at the Chromium bug tracker:

>  It could be that calls to gl.bindBufferRange is slow in Chrome.

At least according to the above performance analysis it looks like this is true.

**Comment by sunag** [comment]
> So even if we use the single UBO approach, we still have to bind the UBO for each object which has a large hit on performance.

The idea behind the my PR wasn't about updating each object individually, but rather a group of objects. We should be handling multiple objects within a single instance of `RenderObject`. The buffer should be shared between similar objects and updated only once per render call. This requires a change to the architecture we're working on; part of it was implemented in the PR, but the group management still needs some polishing. If we reduce the number of GPU calls, we'll solve this issue.

**Comment by Mugen87** [comment]
I just hope Chromium is somehow able to speed up the `gl.bindBufferBase()` calls 😇 .

**Comment by Mugen87** [comment]
This is just out of curiosity but I wonder why `gl.bindBufferBase()` is that expensive. I was always under the assumption that bind commands like `gl.bindFramebuffer()`, `gl.bindTexture()` or `gl.bindBufferBase()` are basically fast WebGL commands. Engines are still supposed to check if a bind operation is required via caching to avoid redundant operations but I always though binding is just "connecting" resources to certain points. It seems depending on the platform/browser `gl.bindBufferBase()` causes noticeable overhead.

**Comment by greggman** [comment]
IIUC (could be wrong). It's only slow on Metal. It's slow on Metal because the GLSL ES 3.0 UBO layouts are incompatible with Metal MSL layouts and so there's a translation step. That step would need to be optimized to fix.

Given it's only slow on Metal and given that, AFAIK, all Metal devices support WebGPU, does this need to be fixed? Those device will use the WebGPU backend.

**Comment by Mugen87** [comment]
> It's only slow on Metal. 

According to the measurements in https://github.com/mrdoob/three.js/issues/30560#issuecomment-3714978726, the performance difference on Android is also large (19 vs 57 FPS).

But I understand the argument that these devices should use WebGPU now. I'm not sure if there are use cases where developers want to force a WebGL 2 usage for certain reasons (the renderer allows that). In such cases, a more performant WebGL backend would be of course great. On the other side, if this is too complex to improve the performance for Metal, maybe it's more pragmatic to do nothing^^. 

Do we know when Safari will use WebGPU by default?

**Comment by greggman** [comment]
Safari shipped WebGPU by default from last September. ATM you must be running MacOS Tahoe (26) or iOS 26

**Comment by Mugen87** [comment]
Strange, I'm on macOS 26.2 and I still get the "WebGPU isn't available" warning in our examples. They all run with WebGL 2.

**Comment by greggman** [comment]
Do other [webgpu samples](https://webgpu.github.io/webgpu-samples/) run? 

https://webgpureport.org ?

Or maybe you disabled it and forgot? It should be on by default if you click "reset feature flags"

<img width="948" height="712" alt="Image" src="https://github.com/user-attachments/assets/ee8ee664-1b33-4adb-9ada-58ebc864301e" />

**Comment by Mugen87** [comment]
The flags were indeed disabled. I've clicked on "Reset Feature Flags" and now it works. Thanks for the tip!

**Comment by kenrussell** [comment]
@Mugen87 I'm investigating the Chromium bug regarding poor UBO performance https://issues.angleproject.org/issues/459088194 . Just now the examples from #issuecomment-3714978726 above, https://jsfiddle.net/gc38m7u6/ and https://jsfiddle.net/angd4ws8/1/ , stopped working. In all of my installed versions of Chrome they render just white. There are some errors in the console around unclosed / malformed HTML tags but those seem to be coming from JSFiddle itself. Can you help me figure out what's going on?

**Comment by kenrussell** [comment]
Hmm, it started rendering again from JSFiddle's website. Downloading the Fiddle didn't work because it tries to use an import statement outside a module. Self-contained test cases as zip archives are definitely appreciated.

**Comment by Mugen87** [comment]
> Self-contained test cases as zip archives are definitely appreciated.

Understood! In below zip file you find both test cases. One folder is intended for `WebGLRenderer`, the other one for `WebGPURenderer` (with WebGL 2 backend). Both folders contain all dependencies the test cases require.

[test_cases.zip](https://github.com/user-attachments/files/24599091/test_cases.zip)

BTW: The demos at jsfiddle import dependencies over `githack` and that service has unfortunately availability issues from time to time.

**Comment by sridhar-mani** [comment]
https://github.com/sridhar-mani/three-webgpu check if this solves the issue

**Comment by crwlcat** [comment]
I've been migrating a fairly draw-heavy app from `WebGLRenderer` to `WebGPURenderer`. The
WebGPU backend behaves, but the WebGL2 fallback (`forceWebGL: true`) has a measurable CPU
regression on the same scene and the same tile LOD state on r186: `render()` takes 2.88 ms
vs 2.20 ms (+31%), and a frame issues ~2350 GL calls vs ~1300 (+80%).

Almost all of the extra calls are uniform buffer traffic — `bufferSubData` 789 vs 0,
`bindBuffer` 632 vs 0. The reason seems clear: every render item carries its own
object-scope uniforms group, and on the WebGL2 backend each one is uploaded immediately
before its draw, via `gl.bindBuffer(gl.UNIFORM_BUFFER, …)` + `gl.bufferSubData(…)`
(`WebGLBackend.updateBinding`, `src/renderers/webgl-fallback/WebGLBackend.js:1991`, called
from `Bindings._update`, `src/renderers/common/Bindings.js:399`). Classic three uploads the
same transforms as plain `gl.uniform*` calls and only creates UBOs when a material sets
`uniformsGroups` (`src/renderers/WebGLRenderer.js:2816`). Since the WebGL backend runs the
updates inline with the draws (no queued pass), the driver sees update→draw interleaving.

This isn't just a migration artifact: Quest ships the WebGL2 backend because Meta's
WebGPU+WebXR renders black there, and it's what people get on browsers without WebGPU.

Measurements: M4 Max on macOS, Chrome/ANGLE-Metal, browser pinned to E-cores so the
submission cost is visible; 376–383 draws, ~3.45 M triangles, identical LOD on both
renderers. Present cadence is identical (that bench is GPU-process-gated), so this is
CPU/driver-call overhead, not frame-rate noise. Per frame:

| | WebGL2 backend | classic WebGLRenderer | Δ |
|---|---|---|---|
| CPU submit | 2.88 ms | 2.20 ms | **+31%** |
| `bufferSubData` | 789 | 0 | +789 |
| `bindBuffer` | 632 | 0 | +632 |
| `uniform*` | 0 | ~470 | −470 |
| `useProgram` / `bindVertexArray` | 42 / 355 | 18 / 282 | 2.3× / +26% |
| total GL calls | ~2350 | ~1300 | **+80%** |

Material-first sorting helps the state churn but not the uploads: restoring the classic
opaque sort brought `useProgram` 42→18 and total calls 2350 → 2000 (submit 2.53 ms), while
`bufferSubData` stayed at 756/frame. That's expected — a moving camera changes every
object's `modelViewMatrix` each frame, and `Object3D.static` doesn't skip the per-object
update yet (the check in `RenderObject.js:917` is commented out).

Would a WebGL counterpart to #27388 be reasonable — one shared object-uniform buffer per
frame with `gl.bindBufferRange()` per draw (16 KB ranges are legal inside a larger buffer)?
Even a smaller step would help: don't rebind a buffer that's already bound, and skip groups
whose values didn't change. Until then, plain `gl.uniform*` for object scope looks cheaper,
at least on ANGLE-Metal and (per #30560) on Android.
