### ISSUE TITLE
WebGPURenderer: on camera switch the shader of skinned mesh is recompiled unnecessarily

### ISSUE THREAD

**Issue by SebastianTusk** [mrdoob/three.js#32524]
### Description

On rendering with a secondary camera the shader of a skinned mesh gets regenerated. There might be circumstances where this is necessary (no idea). But in the general case the generated shader is (almost) identically to the previously generated one. The only difference is the unnecessary renumbering of  the bone buffer. e.g.
```
uniform NodeBuffer_1179 {
	mat4 buffer1179[2];
};
```
[GLSLNodeBuilder.js#L1575](https://github.com/mrdoob/three.js/blob/733f7abc2378874b0c386010b675b7a43f5c6aa5/src/renderers/webgl-fallback/nodes/GLSLNodeBuilder.js#L1575)
The number comes from `node.id` and changes. Otherwise the shader is unchanged. But it is triggering a cache miss and therefore a recompile.

### Reproduction steps

1. Use the WebGL backend. WebGPURenderer({ forceWebGL: true })
2. Have two cameras.
3. Have a skinned mesh.
4. Watch WebGLBackend._completeCompile with a breakpoint.
5. Switch between cameras.
6. Observe WebGLBackend._completeCompile being called twice for the same object and material.

### Code

```js
// code goes here
```

### Live example

https://jsfiddle.net/1byfwaj4/

### Version

0.181.2

### Device

Desktop

### Browser

Chrome

### OS

Windows

**Comment by Mugen87** [comment]
@sunag I think we should reconsider if we need separate render contexts for different cameras. That is a convention from `WebGLRenderer` which is used to easier distinct between different light uniforms (because they are partly view dependent). However, from a structural point of view cameras always have the same set of uniforms so there is basically no need to have separate render objects for each camera.

I have not though this idea fully through yet but it's maybe worth to investigate this option.

**Comment by sunag** [comment]
Yes, it's worth reviewing. I think at the time it was to optimize internal renderings, such as shadows and reflections that share the same scene, but later the `RenderTarget` hash was added, which makes more sense for most cases the camera shouldn't have so much influence. 

Perhaps combining it with `camera.type` instead of `Camera` just to differentiate between `Orthographic` and `Perspective` could help with performance.

**Comment by SebastianTusk** [comment]
Please keep in mind that the core of this issue isn't the camera but that identically TSL materials get translated into differing GLSL/WGSL shaders. This issue would also occur if you e.g. construct the same TSL structures twice.

**Comment by sunag** [comment]
The discussion isn't about the bug, it's about the architecture. The bug only highlights some things that we could improve internally.

**Comment by Mugen87** [comment]
After #32546 and #32557 the performance issue should be fixed.

**Comment by SebastianTusk** [comment]
> Please keep in mind that the core of this issue isn't the camera but that identically TSL materials get translated into differing GLSL/WGSL shaders. This issue would also occur if you e.g. construct the same TSL structures twice.

I would like to remind you that the underlying issue is still present.

**Comment by Mugen87** [comment]
Indeed, we have still #32527 for tracking this issue. I have also left your PR open for further reference.
