### ISSUE TITLE
KTX2 texture with material.alphaHash = true renders artifacts

### ISSUE THREAD

**Issue by upisfree** [mrdoob/three.js#32533]
### Description

If I am using KTX2 texture with material.alphaHash = true there's visual artifacts like semi-transparent noise. If I am using webp version of the texture, it's fine. This problem appears only on Windows, no such problem on macOS and iOS or iPadOS. I don't know in what texture format ktx2 transcodes on Windows, but seems like problem only with it.
If I disable alphaHash and enable material.transparent = true, there's no artifacts even with ktx2 texture.

I am using ktx2 UASTC with UASTC Zstandard supercompression and pregenerated mipmaps.

Here's ktx2 file from live example: https://guga.lol/media/2500b15c-64ee-4f8c-a055-f3fc26b19058.ktx2
And it's webp original: https://guga.lol/media/2500b15c-64ee-4f8c-a055-f3fc26b19058.webp

### Reproduction steps

1. material.alphaHash = true
2. material.map = ktx2Texture
3. Noise artifacts on Windows

### Live example

https://guga.lol

Enter name "hello", login (no registration needed) and you will see semi-transparent noise on your avatar. When moving it more obvious. On static images it appears too.

If you want access to texture from devtools, you can do it by typing `guga.me.media.texture` in console.

### Screenshots

<img width="1739" height="1305" alt="Image" src="https://github.com/user-attachments/assets/d4f5e2c6-e189-42da-a27b-570808389ca2" />

<img width="1739" height="1305" alt="Image" src="https://github.com/user-attachments/assets/a30bff78-6744-48fe-b0cc-d8543367e99a" />

### Version

r182

### Device

Desktop

### Browser

Chrome

### OS

Windows

**Comment by donmccurdy** [comment]
@upisfree could you share the values of `texture.type` and `texture.format` after loading this texture on your Windows device? If the texture was created synchronously (returned directly by `texture = loader.load(url, onLoad, ...)`), then you'll need to wait for the onLoad callback or `loader.loadAsync(url)` promise to resolve, before printing those properties.

**Comment by upisfree** [comment]
@donmccurdy sure!
type = UnsignedByteType = 1009
format = RGBA_BPTC_Format = 36492

tested on
- Windows 11, Nvidia GeForce 3060 Ti
- Windows 11, Nvidia GeForce 5070
- some random AMD GPU

**Comment by Mugen87** [comment]
Can you please try to modfying below line in `KTX2Loader` and set `bptcSupported` to `false`.

https://github.com/mrdoob/three.js/blob/adf4a950c4b5bffb883cd6717d8eeee38bd397f1/examples/jsm/loaders/KTX2Loader.js#L249

This should force the loader to transcode to a different texture format. Since you are on Windows, it would be interesting to see if S3TC exhibits the same issue.

**Comment by donmccurdy** [comment]
Possibly the same issue reproduced on macOS (M1) ... if we modify the [`loader / texture / ktx2`](https://threejs.org/examples/?q=ktx2#webgl_loader_texture_ktx2) example:

```javascript
mesh.material.alphaHash = true;
mesh.material.opacity = 0.5;
```

<img width="2054" height="1516" alt="Image" src="https://github.com/user-attachments/assets/b8aebe61-3246-4db9-b127-5018423b14a1" />

Same result in Chrome, Safari, and Firefox. The horizontal stripes should not be there. BC3 does support an alpha channel — I have no idea why alpha hashing would behave differently for this texture format. 😕

**Comment by upisfree** [comment]
@Mugen87 Windows 11, Chrome 143

set `bptcSupported = false`, no noise:
result texture.type = UnsignedByteType = 1009
trexture.format = RGBA_S3TC_DXT5_Format = 33779

<img width="1440" height="1305" alt="Image" src="https://github.com/user-attachments/assets/e588aa8e-85be-4ad5-ad40-0fe6d475195d" />

**Comment by upisfree** [comment]
@donmccurdy same result on Windows:

<img width="1038" height="772" alt="Image" src="https://github.com/user-attachments/assets/ae1119df-5b4d-485f-9089-93f62fda9da8" />

**Comment by Mugen87** [comment]
> set bptcSupported = false, no noise:

Good to hear! At least you have a workaround now.

> BC3 does support an alpha channel — I have no idea why alpha hashing would behave differently for this texture format.

Maybe it's an option to file an bug at the Chromium bug tracker and see what the Chromium devs think about this issue. The modified `webgl_loader_texture_ktx2` would be an good reproduction case.

**Comment by donmccurdy** [comment]
Similar result if i disable alpha hashing and use alpha blending instead:

<img width="2008" height="1214" alt="Image" src="https://github.com/user-attachments/assets/7253fd07-296a-4498-b3bc-6f40c31b1e5c" />

Output of `ktx info` shows `vkFormat: VK_FORMAT_BC3_SRGB_BLOCK` and...

```plaintext
Data Format Descriptor

DFD total bytes: 60
Vendor ID: KHR_DF_VENDORID_KHRONOS
Descriptor type: KHR_DF_KHR_DESCRIPTORTYPE_BASICFORMAT
Version: KHR_DF_VERSIONNUMBER_1_3
Descriptor block size: 56
Flags: 0x0 (KHR_DF_FLAG_ALPHA_STRAIGHT)
Transfer: KHR_DF_TRANSFER_SRGB
Primaries: KHR_DF_PRIMARIES_BT709
Model: KHR_DF_MODEL_BC3
Dimensions: 4, 4, 1, 1
Plane bytes: 16, 0, 0, 0, 0, 0, 0, 0
Sample 0:
    Qualifiers: 0x10 (KHR_DF_SAMPLE_DATATYPE_LINEAR)
    Channel Type: 0xF (KHR_DF_CHANNEL_BC3_ALPHA)
    Length: 64 bits Offset: 0
    Position: 0, 0, 0, 0
    Lower: 0x00000000
    Upper: 0xffffffff
Sample 1:
    Qualifiers: 0x0 ()
    Channel Type: 0x0 (KHR_DF_CHANNEL_BC3_COLOR)
    Length: 64 bits Offset: 64
    Position: 0, 0, 0, 0
    Lower: 0x00000000
    Upper: 0xffffffff
```

... so I believe there is an alpha channel present. All examples in this thread were transcoded to BC3 from Basis Universal data, which could be a factor too.

**Comment by Mugen87** [comment]
Um, could this also be an issue in the transcoder? Maybe the alpha channel is filled with wrong data.

**Comment by donmccurdy** [comment]
That's possible, especially since the issue seems consistent across browsers and platforms. The BC3 sample was created with KTX2 Software by first encoding to UASTC and then transcoding to BC3, but I think KTX Software uses the Binomial transcoder internally. Three.js uses the Binomial transcoder (currently v1.50) directly. I'll try reporting an issue upstream.

Aside - we should test on https://github.com/mrdoob/three.js/blob/dev/examples/textures/compressed/lensflare_BC3.ktx as well, or other samples NOT created with BasisU. It can be upgraded from KTX to KTX2 with the `ktx2ktx2` CLI utility from KTX Software. Haven't tested this yet but will when I have the chance.

**Comment by upisfree** [comment]
I used wasm version of Binomial transcoder directly, not KTX Software, if it matters.

**Comment by donmccurdy** [comment]
After converting the `lensflare_BC3.ktx` file to KTX2, it doesn't replicate the same issues. I'll continue with reporting an issue upstream.

<details>

<summary><code>ktx info lensflare_BC3.ktx2</code> output</summary>

```
Validation successful

Header

identifier: «KTX 20»\r\n\x1A\n
vkFormat: VK_FORMAT_BC3_UNORM_BLOCK

...

Data Format Descriptor

DFD total bytes: 60
Vendor ID: KHR_DF_VENDORID_KHRONOS
Descriptor type: KHR_DF_KHR_DESCRIPTORTYPE_BASICFORMAT
Version: KHR_DF_VERSIONNUMBER_1_3
Descriptor block size: 56
Flags: 0x0 (KHR_DF_FLAG_ALPHA_STRAIGHT)
Transfer: KHR_DF_TRANSFER_LINEAR
Primaries: KHR_DF_PRIMARIES_BT709
Model: KHR_DF_MODEL_BC3
Dimensions: 4, 4, 1, 1
Plane bytes: 16, 0, 0, 0, 0, 0, 0, 0
Sample 0:
    Qualifiers: 0x0 ()
    Channel Type: 0xF (KHR_DF_CHANNEL_BC3_ALPHA)
    Length: 64 bits Offset: 0
    Position: 0, 0, 0, 0
    Lower: 0x00000000
    Upper: 0xffffffff
Sample 1:
    Qualifiers: 0x0 ()
    Channel Type: 0x0 (KHR_DF_CHANNEL_BC3_COLOR)
    Length: 64 bits Offset: 64
    Position: 0, 0, 0, 0
    Lower: 0x00000000
    Upper: 0xffffffff
```

</details>

> **EDIT:** Initial report filed at https://github.com/KhronosGroup/KTX-Software/issues/1106.

**Comment by donmccurdy** [comment]
> After converting the lensflare_BC3.ktx file to KTX2, it doesn't replicate the same issues...

I was incorrect, the issues are present for the older BC3 file too, but didn't appear visually in the same way. So, we do have a bug in loading BC3-compressed KTX2 files in three.js. Fix proposed in #32772.

@upisfree unfortunately I think the bug that I've identified here, and alpha channel artifacts in your Basis UASTC texture, are two different things. The latter is — I suspect — loss in transcoding from UASTC to BC3. I don't know whether a less-lossy transcode of alpha to BC3 is possible, or if this is expected, that might be a question for the Binomial folks developing Basis Universal. Given that this texture does not actually use any alpha channel, would it be an option to either encode the texture without the alpha channel, or to disable alpha hashing for textures that do not require it?

**Comment by upisfree** [comment]
@donmccurdy unfortunately, in my case, the player can use literally any texture, and it's often semi-transparent, so I can't turn off the alpha channel. I also can't turn off `alphaHash `because other sorting methods for semi-transparent objects produce even more noticeable artifacts.

You mentioned transcoding from UASTC to BC3, but as far as I know, there's no way to configure KTX2Loader and set such parameters. So, is it possible to somehow configure the Basis transcoder for something like this?

Anyway, thank you very much. I've currently fixed this noise in production by setting `ktx2Loader.workerConfig.bptcSupported = false`

**Comment by donmccurdy** [comment]
> You mentioned transcoding from UASTC to BC3, but as far as I know, there's no way to configure KTX2Loader and set such parameters...

What three.js controls at this step is just the target format, so overriding `bptcSupported` as you're doing now is a fine solution, if you know the material will use alpha hashing and you're not sure whether the texture 'should' contain transparency. Once BC3 is selected, I'm not aware of any options controlling how the transcoder works.

> ...the player can use literally any texture, and it's often semi-transparent, so I can't turn off the alpha channel.

Does the player upload a source texture, and then you're compressing it to KTX2? Or the player might provide KTX2 textures directly? If you're doing the compression then another option might be to detect whether the source file actually contains any transparent pixels, and then configure the KTX2 compression accordingly:

```bash
# RGB
ktx create --format R8G8B8_SRGB --encode uastc in.png out.ktx2

# RGB + alpha
ktx create --format R8G8B8A8_SRGB --encode uastc in.png out.ktx2
```

Without alpha the transcoder will select BC1 instead of BC3 automatically, and should avoid this issue.

**Comment by MarkCallow** [comment]
I think this either _is_ due to the mistaken format mapping fixed in https://github.com/mrdoob/three.js/pull/32772 or is an issue with the alphaHash function. I did

```
ktx transcode --target bc3 2500b15c-64ee-4f8c-a055-f3fc26b19058.ktx2 issue_bc3.ktx2
```

to make a bc3 version of ktx2 file then displayed it in my WebGL viewer with alpha blending enabled and a white background.

<img width="950" height="718" alt="Image" src="https://github.com/user-attachments/assets/bf660ebb-ab4b-47cd-8cf6-525f17b387eb" />

No sign of the white speckles so no problem with the transcoded BC3 texture.

**Comment by upisfree** [comment]
> I think this either is due to the mistaken format mapping fixed in https://github.com/mrdoob/three.js/pull/32772 or is an issue with the alphaHash function.

I tested #32772 fix and issue with white speckles is still present. Maybe it's really something with alphaHash shader...

**Comment by MarkCallow** [comment]
> Maybe it's really something with alphaHash shader...

That is my guess.

**Comment by donmccurdy** [comment]
An implication of alpha hashing is that if alpha values for most pixels were to drop from `1.0` to `1.0 - 1.0 / 255.0`  (for example), then some small number of texels would be discarded entirely. That same change in alpha would likely not be noticeable in an alpha blended material. Because the issue occurs only when transcoding to BC3, that may be what's happening.

I think we may need to read back these alpha values after transcoding, to see if they are different for BC3. If it's a very small difference (<1/255?) then perhaps the alpha hashing shader should include a small epsilon offset.

**Comment by upisfree** [comment]
@donmccurdy by the way maybe if we will have alphaHash epsilon, it will fix another issue that is not related to BC3? Semi transparent textures tend to noise with alpha hash. I know that it's expected with this method of sorting but on semi-transparent textures it's much more visible. On screenshots all textures are PNGs.

<img width="2560" height="1080" alt="Image" src="https://github.com/user-attachments/assets/0a97e079-c4c4-432d-9131-a26c0ce5af0d" />

`alphaHash = true`

<img width="2560" height="1080" alt="Image" src="https://github.com/user-attachments/assets/9d2a18e6-5b98-4b2f-8d42-ba7adc6801e6" />

`alphaHash = false`
