### ISSUE TITLE
r73: Report error

### ISSUE THREAD

**Issue by Freeman555** [mrdoob/three.js#7368]
Hi there!

I've found some;
->Loader.createMaterial: Unsupported colorAmbient
![r_73](https://cloud.githubusercontent.com/assets/15048451/10561643/cce2abb6-7532-11e5-8602-f535079a1930.PNG)
[working on r72](http://jsfiddle.net/Freeman555/jopLhx5g/)

[not r73](http://jsfiddle.net/Freeman555/f14pa7gr/)

**Comment by WestLangley** [comment]
Remove

     "colorAmbient": [0.8,0.8,0.8],

from your json file.

**Comment by Freeman555** [comment]
@WestLangley works, THX [r73 jsfiddle](http://jsfiddle.net/Freeman555/f14pa7gr/1/)
@mrdoob Three.js Blender Export will be updated without these issue?

**Comment by yomotsu** [comment]
It should be fixed at next rev!
https://github.com/mrdoob/three.js/pull/7374

**Comment by Freeman555** [comment]
Cool, so I close it.

**Comment by mrdoob** [comment]
I refactored `Loader.createMaterial`. `colorAmbient` should have been a warning instead of an error. Will fix!

**Comment by SET001** [comment]
If I just remove `colorAmbient` and also if I will update and use latest blender exporter (from dev) I will end up with with with messed colors.

http://stackoverflow.com/questions/33461750/how-does-materials-work-exported-from-json


![](http://i.stack.imgur.com/rU0zs.png)

**Comment by mrdoob** [comment]
That's fixed in `dev` too. Sorry about that.

**Comment by SET001** [comment]
@mrdoob but I switched to 74dev and still experiencing this. Maybe I'm doing something wrong?

**Comment by mrdoob** [comment]
Could you share the exported model?

**Comment by SET001** [comment]
yes, sure - http://pastebin.com/J7pVVRbt
this is a json file from latest blender exporter from dev branch

**Comment by yomotsu** [comment]
I think @SET001 's question is not a bug. It seems your JSON missing colorDiffuse and uvs or VertexColor.

Make sure to check the exporter setting, and this question supposed be posted Stack Overflow.

**Comment by mrdoob** [comment]
@yomotsu thanks!

**Comment by SET001** [comment]
@yomotsu thanx  )

**Comment by mrdoob** [comment]
@yomotsu I'm thinking I should remove support for DbgColor as I an only see it causing confusion like this. What do you think?

**Comment by yomotsu** [comment]
@mrdoob That is fine for me. I don't think it is helpful too...
Actually I don't know the purpose of `DbgColor `. It is just generated [while making `materials` array](https://github.com/mrdoob/three.js/blob/317d6f66542ab63323c5dab6c7a4e9d08c07ca05/utils/exporters/blender/addons/io_three/exporter/api/mesh.py#L522), using [lookup](https://github.com/mrdoob/three.js/blob/317d6f66542ab63323c5dab6c7a4e9d08c07ca05/utils/exporters/blender/addons/io_three/constants.py#L369).

I'm not sure but might be for compatibility with other converters like [this](https://github.com/mrdoob/three.js/blob/af21991fc7c4e1d35d6a93031707273d937af0f9/utils/converters/obj/convert_obj_three.py#L921)

**Comment by anzorb** [comment]
We have hundreds of JSON models in production, and are currently migrating to r73, this error is flooding the console, even though it has no effect on our models or textures, can't we add it to the switch and console.warn instead? Feels like a 'rough' migration otherwise, when it doesn't harm to have this property (especially for projects that may need backwards compatibility). I can submit PR if I get the green light.
