### ISSUE TITLE
ColladaLoader issue: THREE.BufferAttribute.copyVector3sArray(): vector is undefined

### ISSUE THREAD

**Issue by SamNPowers** [mrdoob/three.js#7388]
I have two dae files that, when they're both loaded via colladaLoader, cause a lot of this error:
THREE.BufferAttribute.copyVector3sArray(): vector is undefined.

The snowflake model is also visibly corrupted.

If only one of them is loaded, it's fine. It only seems to happen when they're both loaded. I saw there's a ColladaLoader2 in the repo. This loader did not have the issue (they both loaded fine), but the colors of my objects were all incorrect.

GitHub doesn't support attaching dae files, so I changed their file types to png:

pointyavatar:
https://cloud.githubusercontent.com/assets/881718/10623976/24a49ed2-7762-11e5-891a-e94d745a8c2d.png
snowflake:
https://cloud.githubusercontent.com/assets/881718/10623979/2862b04a-7762-11e5-989a-3b49881cf2d6.png

I can link to a complete repro, if that would be preferred.

**Comment by mrdoob** [comment]
I've pushed an old version of `ColladaLoader` to `dev`. Do you mind trying with that one?

**Comment by SamNPowers** [comment]
Tried, still fails.

Just to be 100% sure I tried the right one, I used this:
https://raw.githubusercontent.com/mrdoob/three.js/dev/examples/js/loaders/ColladaLoader.js

**Comment by mrdoob** [comment]
That seems to be the right one. Can you share the dae files?

**Comment by SamNPowers** [comment]
GitHub wouldn't let me attach dae files, so I attached them as png files in my original bug. Let me know if you can't access them, and I'll send a link. 

-----Original Message-----

**Comment by mrdoob** [comment]
Ah, I see, next time rename them to TXT 😉

**Comment by mrdoob** [comment]
You must be having a cache issue. I've just loaded both .dae in the editor and they seem to display correctly.

![screen shot 2015-10-21 at 16 24 06](https://cloud.githubusercontent.com/assets/97088/10649121/4220c036-7810-11e5-96fd-9aa3167681b8.png)

**Comment by SamNPowers** [comment]
Hmm. I tested it on a friend's computer, in addition to trying multiple browsers and clearing my cache. Perhaps I am using colladaLoader in a way that was not intended.

My repro is here:
http://www.figmentory.com/client/old/BrokenCollada.html

Interestingly, it did seem to work once. But when I refreshed the page, it was broken again.

**Comment by mrdoob** [comment]
Hmm... Try removing this line?

```js
colladaLoader.options.convertUpAxis = true
```

**Comment by SamNPowers** [comment]
Still seeing the issue, even with that line removed, unfortunately.

**Comment by mrdoob** [comment]
Ok. Seems like this is a design problem of the loader.
The problem goes away if you create a `ColladaLoader` per model.

```javascript
var colladaLoader = new THREE.ColladaLoader();
colladaLoader.options.convertUpAxis = true;
colladaLoader.load('assets/PointyAvatar.dae', function(colladaObj) {

	scene.add(colladaObj.scene);
	//asset.position.copy(previewRoomPos);

});

var colladaLoader = new THREE.ColladaLoader();
colladaLoader.options.convertUpAxis = true;
colladaLoader.load('assets/snowflake.dae', function(colladaObj) {

	scene.add(colladaObj.scene);
	//asset.position.copy(previewRoomPos);

});
```

This won't be a problem with `ColladaLoader2`. Hoping to be able to add more features in the coming weeks!

**Comment by coral** [comment]
Sadly still is a problem with dual loaders.

**Comment by mrdoob** [comment]
Really? Seems to work fine here...?

**Comment by Code141** [comment]
Hi, I have exactly the same probleme.
My code is styructured something like that : 
```javascript
MODELS = new Array();

manager = new THREE.LoadingManager();

manager.onLoad = function(){
tank1 = MODELS["tank"].clone();
tank2 = MODELS["tank"].clone();
heal1 = MODELS["heal"].clone();
heal2 = MODELS["heal"].clone();

scene.add(tank1, tank2, heal1, heal2);
}

function load(name, daePath){
	loader = new THREE.ColladaLoader(manager);
	loader.options.convertUpAxis = true;
	loader.load(daePath, function(collada) {
		MODELS[name] = collada.scene;
	}, function(progress) {
            // show some progress
        });
}

load("tank", './models/tank.dae');
load("heal", './models/heal.dae');
```
Model build by blender.
I have noticed that only the first model loaded if fine, when I load more models, the second is blended with the first and he is bugged...
When I rename into blender, the geometrie of each mesh by a unique name, that don't bug anymore...
I have try to load my .dae into http://threejs.org/editor/ and the same probleme happend. Until I have rennamed the geometry layers into the outliner windows in blender...
And for finish, if I load multiple mesh, the bug happend only when the camera look on the object.
I'm just starting modelling so I maybe do something wrong in blender exporting collada.
In fact, it work now, but I think it isn't normal to have to give a name of all geometry into blender soft... But as I have said it, I probably do something wrong.
Ps: I have tryed to remove convertUpAxis. No change.

**Comment by mrdoob** [comment]
Try using the ColladaLoder in the dev branch.
https://github.com/mrdoob/three.js/blob/dev/examples/js/loaders/ColladaLoader.js

**Comment by Code141** [comment]
It's work ! But :
-loading manager do not work anymore by the way I used it
-my objects had multiple materials applied on face. Now, one material by mesh is applied (not really important for me but maybe it isn't the comportement that you wanna reach)
Thanks for your fabulous library, and thanks for the speed of support.

**Comment by mrdoob** [comment]
Unfortunately, until `ColladaLoader2` reaches feature parity, we're stuck with `ColladaLoder` not having `LoadingManager` support 😕

**Comment by Code141** [comment]
Okay, so I'm gonna continue to use the ColladaLoader v1 (with the renaming geometry trick) Because I don't know how to simply manage multiple loading before init all my app...
Maybe Three.js got any loader more mature for others system file ? .obj ?
An idea of when ColladaLoader2 will be release ?

**Comment by blakeaross** [comment]
@mrdoob I am experiencing this same issue. I'm building a project set to launch soon for one of the world's most recognized brands, and we are employing threejs as our means to let the user manipulate 3D versions of their products. I can't seem to make any headway on this exact bug. Doob, what's the chance that you and I could get on the phone for a few minutes? If you're not cool with that level of support, how could I run my situation by you without disclosing this brand's work to the internet at large / this forum? My email is blake.ross@jacksonmg.com if you're free to reach out that way.

**Comment by mrdoob** [comment]
Do you mind trying `ColladaLoader` and/or `ColladaLoader2` from the `dev` branch?

**Comment by blakeaross** [comment]
I have done that this morning, but it didn't correct the problem, though perhaps if I had stuck with it I could have gotten one of those two versions to work; perhaps it was an error on my part.

Because I'm trying to get this to client for review by EOD, I went ahead and started going into each product's model and renaming the meshes, and that is allowing threejs to load & remove all the models while playing nicely with angular. So since I have an adequate solution, we don't need to jump on the phone for urgent support. Thank you.

**Comment by mrdoob** [comment]
Glad that you figured out a way. Good luck with the deadline!

**Comment by andrevenancio** [comment]
Having similar problem!
Code/explanation here: http://stackoverflow.com/questions/34278210/three-explodemodifier-hacking

**Comment by sakiman1212** [comment]
@mrdoob I transitioned to ColladaLoader2.js based on the same issues described in this thread -- but after doing so, I'm experiencing the random color issue reported by the OP. Colors are being applied at random to the objects in my .dae file (with each page refresh) and shadows have disappeared. It's as if ColladaLoader2.js is ignoring the color settings in the .dae file and just randomly applying a color instead (not to mention the shadow issue). I've detailed the issue here with a few example links - thanks for the support! 
http://stackoverflow.com/questions/34715525/colladaloader2-js-random-colors-are-overwriting-dae-file-settings-three-js

**Comment by mrdoob** [comment]
@sakiman1212 make sure you're using the latest `ColladaLoader2`. https://github.com/mrdoob/three.js/blob/dev/examples/js/loaders/ColladaLoader2.js

**Comment by sakiman1212** [comment]
Thank you! @mrdoob The source I was checking for the latest ColladaLoader2.js file must have been incorrect.

**Comment by EliasHasle** [comment]
@Code141 I have the same issue. The very unsatisfactory solution for me is to downgrade to R72 of THREE and ColladaLoader. But I am not certain that the problem is caused by the ColladaLoader, because the models (exported from Blender) did not validate perfectly with xmllint (Collada schema 1.4.1). It may (in my case) be an issue of differing assumptions for incomplete models, that the new version (R74) makes other assumptions than the old one (R72). Here is a .dae file (renamed to .txt) that shows as red and grey/white in R72 and as only red in R74:
[cargoHold1.txt](https://github.com/mrdoob/three.js/files/164479/cargoHold1.txt)

**Comment by 123names** [comment]
will, same issue here, 
![image](https://cloud.githubusercontent.com/assets/13399367/14235740/99c40eba-f9d4-11e5-8f57-e118ff176d08.png)

**Comment by Code141** [comment]
@EliasHasle Use the MrDoob ColladaLoader2.js, ain't no probleme anymore for me with that...

**Comment by 123names** [comment]
will, i delete web cache the restart the local server then it worked, but i do not know if it will happen again or not, because i reset everything few time and only work for while. hope not happen again. However if it happen again, i will try the ColladaLoader2.js.
